my_tup = ()
print(my_tup)
my_tup = (1, 2, 3)
print(my_tup)
my_tup=(1, "HI", 5.9)
print(my_tup)
my_tup = ("cat", [3, 7, 9], (5, 6, 7))
print(my_tup)
my_tup = ("h", "e", "l", "l", "o" )
print(my_tup[0])
print(my_tup[4])
n_tup = ("mouse", [8, 6, 4], (1, 2, 3))
print(n_tup[0][3])
print(n_tup[1][1])
print("sliced: ", my_tup[1:4])
for letter in (my_tup):
    print("hello", letter)